title: "Momster Monologues"
tagline: "Unfiltered, hilarious dispatches from the beautiful chaos of modern motherhood."
logo: "mm.jpg"

description: "Unfiltered, hilarious dispatches from the beautiful chaos of modern motherhood."

url: "https://momstermonologues.github.io"
baseurl: ""  # or "/repo-name" if hosted under a subpath

sass:
  sass_dir: _sass

navigation:
  - text: "Home"
    url: "/"
  - text: "About Me"
    url: "/about/"
  - text: "Contact"
    url: "/contact/"
  - text: "Services"
    url: "/services/"
  - text: "Podcast"
    url: "/podcast/"
  - text: "Blog"
    url: "/blog/"

author:
  name: "Vasti Tait"
  bio: "Vasti Tait is the founder and creative director of Momster Monologues."
  url: "https://www.instagram.com/vastitait/"
  location: "South Africa"
  image: "me.jpg"

social:
  facebook: "momstermonologues"
  instagram: "momstermonologues"
  youtube: "MomsterMonologues"
  email: "momstermonologues@gmail.com"
  pinterest: "momstermonologues"
  substack: "momstermonologues"
  tiktok: "momster.monologues"

paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate

permalink: pretty

markdown: kramdown
kramdown:
  auto_ids: false
