title: Momster Monologues
logo: /assets/images/logo.jpg
baseurl: /momster-monologues.github.io

##
# Typewritter configuration.
# Feel free to disable if you don't like it.
##
typewriter_effect: true

##
# Collections configuration
##
collections:
  projects:
    output: true

##
# Contact Channels configuration
# Uncomment for enable. Available contact channels are email, github, telegram, stackoverflow, discord, mastodon.
# Please fell free to send a PR if you need a new one.
# DISABLE GITHUB setting it as an empty string: ""
# if false, then no contact channels will be display.
##
contact_channels_section: true
contact_channels:
  email: "momstermonologues@gmail.com"
  instagram: "https://www.instagram.com/momstermonologues"
  facebook: "https://www.facebook.com/momstermonologues"
  pinterest: "https://www.pinterest.com/momstermonologues"
  substack: "https://momstermonologues.substack.com"
  tiktok: "https://www.tiktok.com/@momstermonologues"
  youtube: "https://www.youtube.com/@momstermonologues"

##
# Plugins configuration
##
plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-polyglot

##
# Polyglot configuration
##
languages: ["en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

##
# Archives configuration
##
jekyll-archives:
  enabled:
    - categories
  layout: blog
  permalinks:
    category: "/category/:name/"
